FROM ubuntu:24.04
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get -y install --no-install-recommends \
  python3-pip python3 python3-venv \
  && apt-get clean

RUN python3 -m venv /venv && /venv/bin/pip install --no-cache awsiotsdk

COPY --chmod=755 publish_to_iot_core.py /bin/publish_to_iot_core.py

CMD ["/bin/sh", "-c", "/venv/bin/python3 /bin/publish_to_iot_core.py"]
