#!/bin/sh

set -e

systemd-tmpfiles --create

systemctl enable greengrass-lite.target
systemctl enable ggl.aws_iot_tes.socket
systemctl enable ggl.aws_iot_mqtt.socket
systemctl enable ggl.gg_config.socket
systemctl enable ggl.gg_health.socket
systemctl enable ggl.gg_fleet_status.socket
systemctl enable ggl.gg_deployment.socket
systemctl enable ggl.gg_pubsub.socket
systemctl enable ggl.gg-ipc.socket.socket
systemctl enable ggl.core.ggconfigd.service
systemctl enable ggl.core.iotcored.service
systemctl enable ggl.core.tesd.service
systemctl enable ggl.core.ggdeploymentd.service
systemctl enable ggl.core.gg-fleet-statusd.service
systemctl enable ggl.core.ggpubsubd.service
systemctl enable ggl.core.gghealthd.service
systemctl enable ggl.core.ggipcd.service
systemctl reset-failed
systemctl daemon-reload
systemctl start greengrass-lite.target
