FROM ubuntu:24.04
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get -y install --no-install-recommends \
    systemd systemd-sysv ca-certificates sudo nano bash-completion \
    build-essential pkg-config cmake git \
  && apt-get clean
RUN apt-get -y install --no-install-recommends \
    libssl-dev libcurl4-openssl-dev libsqlite3-dev libyaml-dev \
    libsystemd-dev liburiparser-dev uuid-dev libevent-dev \
  && apt-get clean

COPY ./getty-override.conf \
  /etc/systemd/system/console-getty.service.d/override.conf

RUN groupadd ggc_group && useradd -Ng ggc_group ggc_user

RUN echo "export MAKEFLAGS=-j" >> /root/.profile

CMD ["/lib/systemd/systemd"]
